"""Authentication service — multi-user support, dynamic registration codes, audit logging.

Security model:
- Users stored in JSON file on disk (data/auth/users.json)
- Registration codes generated by admin, stored in data/auth/registration_codes.json
- Codes support max_uses and optional expiry
- Passwords hashed with PBKDF2-HMAC-SHA256 (100k iterations)
- Session tokens cryptographically random, in-memory with expiry
- All auth events recorded in audit log (JSONL persisted to disk)
"""
import hashlib
import hmac
import json
import logging
import os
import re
import secrets
import threading
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Dict, List, Any

logger = logging.getLogger(__name__)

DEFAULT_ADMIN_USERNAME = "admin"
DEFAULT_ADMIN_PASSWORD = "ChangeMe!2024"

SESSION_TTL_SECONDS = 8 * 3600
SESSION_COOKIE_NAME = "ecs_session"
MAX_SESSIONS = 50
MAX_AUDIT_ENTRIES = 10000

MIN_PASSWORD_LENGTH = 8
MAX_PASSWORD_LENGTH = 128
USERNAME_PATTERN = re.compile(r"^[a-zA-Z0-9_\-]{3,32}$")

EVENT_TYPES = {
    "LOGIN_SUCCESS":      {"label": "Login Success",      "severity": "info"},
    "LOGIN_FAILURE":      {"label": "Login Failure",      "severity": "warning"},
    "LOGOUT":             {"label": "Logout",             "severity": "info"},
    "SESSION_EXPIRED":    {"label": "Session Expired",    "severity": "info"},
    "USER_REGISTER":      {"label": "User Registered",    "severity": "warning"},
    "PASSWORD_CHANGE":    {"label": "Password Changed",   "severity": "warning"},
    "PASSWORD_RESET":     {"label": "Password Reset",     "severity": "warning"},
    "USER_DEACTIVATED":   {"label": "User Deactivated",   "severity": "error"},
    "USER_ACTIVATED":     {"label": "User Activated",     "severity": "info"},
    "REGCODE_GENERATED":  {"label": "Reg Code Generated", "severity": "info"},
    "REGCODE_REVOKED":    {"label": "Reg Code Revoked",   "severity": "warning"},
    "REGCODE_USED":       {"label": "Reg Code Used",      "severity": "info"},
    "ASSESSMENT_START":   {"label": "Assessment Started", "severity": "info"},
    "ASSESSMENT_COMPLETE":{"label": "Assessment Complete","severity": "info"},
    "ASSESSMENT_CANCEL":  {"label": "Assessment Cancelled","severity": "warning"},
    "ASSESSMENT_FAIL":    {"label": "Assessment Failed",  "severity": "error"},
    "KEYPAIR_GENERATE":   {"label": "Keypair Generated",  "severity": "warning"},
    "SERVER_ADD":         {"label": "Server Added",       "severity": "info"},
    "SERVER_REMOVE":      {"label": "Server Removed",     "severity": "warning"},
    "LLM_CONFIG_UPDATE":  {"label": "LLM Config Updated", "severity": "warning"},
    "LLM_CONFIG_VERIFY":  {"label": "LLM Config Verified","severity": "info"},
    "REPORT_VIEW":        {"label": "Report Viewed",      "severity": "info"},
    "REPORT_DOWNLOAD":    {"label": "Report Downloaded",  "severity": "info"},
    "CHECKLIST_UPLOAD":   {"label": "Checklist Uploaded", "severity": "info"},
    "CHECKLIST_ANALYZE":  {"label": "Checklist Analyzed", "severity": "info"},
    "BENCHMARK_VIEW":     {"label": "Benchmark Viewed",   "severity": "info"},
    "CONFIG_CHANGE":      {"label": "Configuration Changed","severity": "warning"},
}


def _hash_password(password: str, salt: Optional[bytes] = None) -> tuple:
    if salt is None:
        salt = os.urandom(32)
    dk = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, 100_000)
    return salt.hex(), dk.hex()


def _verify_password(password: str, salt_hex: str, hash_hex: str) -> bool:
    salt = bytes.fromhex(salt_hex)
    expected = bytes.fromhex(hash_hex)
    dk = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, 100_000)
    return hmac.compare_digest(dk, expected)


def _validate_password_strength(password: str) -> Optional[str]:
    if len(password) < MIN_PASSWORD_LENGTH:
        return f"Password must be at least {MIN_PASSWORD_LENGTH} characters long"
    if len(password) > MAX_PASSWORD_LENGTH:
        return f"Password must not exceed {MAX_PASSWORD_LENGTH} characters"
    if not re.search(r"[A-Z]", password):
        return "Password must contain at least one uppercase letter"
    if not re.search(r"[a-z]", password):
        return "Password must contain at least one lowercase letter"
    if not re.search(r"\d", password):
        return "Password must contain at least one digit"
    if not re.search(r"[!@#$%^&*()_+\-=\[\]{};':\"\\|,.<>\/?]", password):
        return "Password must contain at least one special character"
    return None


def _validate_username(username: str) -> Optional[str]:
    if not USERNAME_PATTERN.match(username):
        return "Username must be 3-32 characters, alphanumeric/underscore/hyphen only"
    return None


class AuditLog:
    """In-memory + file-persisted audit log with filtering support."""

    def __init__(self, log_file: Optional[Path] = None, max_entries: int = MAX_AUDIT_ENTRIES):
        self._entries: List[Dict[str, Any]] = []
        self._lock = threading.Lock()
        self._log_file = log_file
        self._max_entries = max_entries
        if log_file:
            self._log_file.parent.mkdir(parents=True, exist_ok=True)
            self._load_from_disk()

    def _load_from_disk(self):
        if not self._log_file or not self._log_file.exists():
            return
        try:
            with open(self._log_file, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line:
                        self._entries.append(json.loads(line))
            logger.info(f"Loaded {len(self._entries)} audit entries from disk")
        except Exception as e:
            logger.warning(f"Failed to load audit log: {e}")

    def add(self, event_type: str, username: str = "system",
            ip_address: str = "", details: str = "", extra: Optional[Dict] = None):
        if event_type not in EVENT_TYPES:
            severity = "info"
        else:
            severity = EVENT_TYPES[event_type]["severity"]
        entry = {
            "id": len(self._entries) + 1,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "timestamp_local": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "event_type": event_type,
            "event_label": EVENT_TYPES.get(event_type, {}).get("label", event_type),
            "severity": severity, "username": username, "ip_address": ip_address,
            "details": details, "extra": extra or {},
        }
        with self._lock:
            self._entries.append(entry)
            if len(self._entries) > self._max_entries:
                self._entries = self._entries[-self._max_entries:]
            if self._log_file:
                try:
                    with open(self._log_file, "a", encoding="utf-8") as f:
                        f.write(json.dumps(entry, ensure_ascii=False) + "\n")
                except Exception:
                    pass
        logger.info(f"AUDIT [{event_type}] user={username} ip={ip_address} details={details}")

    def query(self, event_type=None, severity=None, username=None,
              search_text=None, start_date=None, end_date=None, limit=200, offset=0):
        with self._lock:
            entries = list(self._entries)
        filtered = []
        for entry in entries:
            if event_type and entry["event_type"] != event_type: continue
            if severity and entry["severity"] != severity: continue
            if username and entry["username"] != username: continue
            if search_text:
                s = f"{entry['event_type']} {entry['event_label']} {entry['username']} {entry['details']} {entry.get('extra','')}"
                if search_text.lower() not in s.lower(): continue
            if start_date and entry["timestamp_local"] < start_date: continue
            if end_date and entry["timestamp_local"] > end_date + " 23:59:59": continue
            filtered.append(entry)
        filtered.sort(key=lambda x: x["timestamp"], reverse=True)
        return filtered[offset:offset + limit], len(filtered)

    def get_stats(self):
        with self._lock:
            entries = list(self._entries)
        stats = {"total": len(entries), "by_severity": {}, "by_event_type": {}, "last_24h": 0, "last_1h": 0}
        now = time.time()
        for entry in entries:
            stats["by_severity"][entry["severity"]] = stats["by_severity"].get(entry["severity"], 0) + 1
            stats["by_event_type"][entry["event_type"]] = stats["by_event_type"].get(entry["event_type"], 0) + 1
            try:
                ts = datetime.fromisoformat(entry["timestamp"]).timestamp()
                if now - ts < 86400: stats["last_24h"] += 1
                if now - ts < 3600: stats["last_1h"] += 1
            except Exception: pass
        return stats

    def clear(self):
        with self._lock:
            self._entries = []
            if self._log_file and self._log_file.exists(): self._log_file.unlink()


class UserStore:
    """Multi-user store persisted to JSON file on disk."""

    def __init__(self, users_file: Path):
        self._file = users_file
        self._lock = threading.Lock()
        self._users: Dict[str, Dict[str, Any]] = {}
        self._load()

    def _load(self):
        self._file.parent.mkdir(parents=True, exist_ok=True)
        if self._file.exists():
            try:
                with open(self._file, "r", encoding="utf-8") as f:
                    self._users = json.load(f).get("users", {})
                logger.info(f"Loaded {len(self._users)} users from {self._file}")
            except Exception as e:
                logger.warning(f"Failed to load users: {e}")

    def _save(self):
        try:
            with open(self._file, "w", encoding="utf-8") as f:
                json.dump({"users": self._users}, f, indent=2, ensure_ascii=False)
            self._file.chmod(0o600)
        except Exception as e:
            logger.error(f"Failed to save users: {e}")

    def get_user(self, username): 
        with self._lock: return self._users.get(username)

    def list_users(self):
        with self._lock:
            return [{"username": u, "role": d.get("role","user"), "created_at": d.get("created_at",""),
                     "is_active": d.get("is_active",True), "last_login": d.get("last_login","")}
                    for u, d in self._users.items()]

    def add_user(self, username, password, role="user"):
        with self._lock:
            if username in self._users: return False
            s, h = _hash_password(password)
            self._users[username] = {"salt_hex": s, "hash_hex": h, "role": role,
                "created_at": datetime.now(timezone.utc).isoformat(), "is_active": True, "last_login": ""}
            self._save(); return True

    def verify_user(self, username, password):
        with self._lock:
            u = self._users.get(username)
            if not u or not u.get("is_active", True): return None
            if _verify_password(password, u["salt_hex"], u["hash_hex"]):
                return {"username": username, "role": u.get("role", "user")}
            return None

    def change_password(self, username, new_password):
        with self._lock:
            u = self._users.get(username)
            if not u: return False
            s, h = _hash_password(new_password)
            u["salt_hex"], u["hash_hex"] = s, h
            u["password_changed_at"] = datetime.now(timezone.utc).isoformat()
            self._save(); return True

    def verify_password(self, username, password):
        with self._lock:
            u = self._users.get(username)
            return bool(u) and _verify_password(password, u["salt_hex"], u["hash_hex"])

    def update_last_login(self, username):
        with self._lock:
            u = self._users.get(username)
            if u: u["last_login"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S"); self._save()

    def has_admin(self):
        with self._lock: return any(u.get("role") == "admin" for u in self._users.values())

    def count(self):
        with self._lock: return len(self._users)


class RegistrationCodeStore:
    """Admin-generated registration codes persisted to JSON file."""

    def __init__(self, codes_file: Path):
        self._file = codes_file
        self._lock = threading.Lock()
        self._codes: Dict[str, Dict[str, Any]] = {}
        self._load()

    def _load(self):
        self._file.parent.mkdir(parents=True, exist_ok=True)
        if self._file.exists():
            try:
                with open(self._file, "r", encoding="utf-8") as f:
                    self._codes = json.load(f).get("codes", {})
                logger.info(f"Loaded {len(self._codes)} registration codes")
            except Exception as e:
                logger.warning(f"Failed to load reg codes: {e}")

    def _save(self):
        try:
            with open(self._file, "w", encoding="utf-8") as f:
                json.dump({"codes": self._codes}, f, indent=2, ensure_ascii=False)
            self._file.chmod(0o600)
        except Exception as e:
            logger.error(f"Failed to save reg codes: {e}")

    def generate_code(self, created_by: str, max_uses: int = 1,
                      expires_hours: Optional[int] = None, note: str = "") -> str:
        """Generate a new registration code. Returns the code string."""
        code = f"ECS-{secrets.token_urlsafe(16).replace('-', '').replace('_', '')[:20].upper()}"
        with self._lock:
            self._codes[code] = {
                "created_at": datetime.now(timezone.utc).isoformat(),
                "created_by": created_by,
                "max_uses": max_uses,
                "used_count": 0,
                "expires_at": (datetime.now(timezone.utc).timestamp() + expires_hours * 3600)
                    if expires_hours else None,
                "is_active": True,
                "note": note,
                "used_by": [],
            }
            self._save()
        return code

    def validate_code(self, code: str) -> tuple:
        """Validate a registration code. Returns (valid: bool, error: str)."""
        with self._lock:
            entry = self._codes.get(code)
            if not entry:
                return False, "Invalid registration code"
            if not entry.get("is_active", True):
                return False, "This registration code has been revoked"
            if entry["used_count"] >= entry["max_uses"]:
                return False, "This registration code has reached its usage limit"
            if entry.get("expires_at") and time.time() > entry["expires_at"]:
                return False, "This registration code has expired"
            return True, ""

    def consume_code(self, code: str, username: str):
        """Mark a code as used by a username."""
        with self._lock:
            entry = self._codes.get(code)
            if entry:
                entry["used_count"] += 1
                entry["used_by"].append({"username": username,
                                         "used_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")})
                self._save()

    def list_codes(self) -> List[Dict[str, Any]]:
        with self._lock:
            result = []
            for code, entry in self._codes.items():
                is_expired = entry.get("expires_at") and time.time() > entry["expires_at"]
                is_used_up = entry["used_count"] >= entry["max_uses"]
                result.append({
                    "code": code,
                    "created_at": entry.get("created_at", ""),
                    "created_by": entry.get("created_by", ""),
                    "max_uses": entry.get("max_uses", 1),
                    "used_count": entry.get("used_count", 0),
                    "remaining_uses": entry.get("max_uses", 1) - entry.get("used_count", 0),
                    "expires_at": datetime.fromtimestamp(entry["expires_at"]).strftime("%Y-%m-%d %H:%M")
                        if entry.get("expires_at") else None,
                    "is_active": entry.get("is_active", True),
                    "is_expired": is_expired,
                    "is_used_up": is_used_up,
                    "status": "revoked" if not entry.get("is_active", True)
                        else "expired" if is_expired
                        else "used up" if is_used_up
                        else "active",
                    "note": entry.get("note", ""),
                    "used_by": entry.get("used_by", []),
                })
            return result

    def revoke_code(self, code: str) -> bool:
        with self._lock:
            entry = self._codes.get(code)
            if not entry: return False
            entry["is_active"] = False
            self._save()
            return True

    def delete_code(self, code: str) -> bool:
        with self._lock:
            if code not in self._codes: return False
            del self._codes[code]
            self._save()
            return True


class AuthService:
    """Authentication service with multi-user, registration codes, and sessions."""

    def __init__(self, audit: AuditLog, users_file: Optional[Path] = None,
                 codes_file: Optional[Path] = None):
        self.audit = audit
        self._sessions: Dict[str, Dict[str, Any]] = {}
        self._lock = threading.Lock()
        self._user_store = UserStore(users_file) if users_file else None
        self._code_store = RegistrationCodeStore(codes_file) if codes_file else None

        self._default_admin = os.environ.get("ADMIN_USERNAME", DEFAULT_ADMIN_USERNAME)
        password_env = os.environ.get("ADMIN_PASSWORD", DEFAULT_ADMIN_PASSWORD)
        self._default_salt, self._default_hash = _hash_password(password_env)

        if self._user_store and not self._user_store.has_admin():
            if not self._user_store.get_user(self._default_admin):
                self._user_store.add_user(self._default_admin, password_env, role="admin")
                logger.info(f"Created default admin '{self._default_admin}'")

        logger.info(f"Auth service initialized (users: {self._user_store.count() if self._user_store else 'single'})")

    def authenticate(self, username, password, ip_address=""):
        if not username or not password: return None
        user_info = None
        if self._user_store:
            user_info = self._user_store.verify_user(username, password)
        elif username == self._default_admin and _verify_password(password, self._default_salt, self._default_hash):
            user_info = {"username": username, "role": "admin"}
        if user_info:
            token = secrets.token_urlsafe(48)
            now = time.time()
            session = {"token": token, "username": username, "role": user_info.get("role", "user"),
                       "created_at": now, "expires_at": now + SESSION_TTL_SECONDS, "ip_address": ip_address}
            with self._lock:
                self._cleanup_expired()
                self._sessions[token] = session
                if len(self._sessions) > MAX_SESSIONS:
                    del self._sessions[min(self._sessions, key=lambda t: self._sessions[t]["created_at"])]
            if self._user_store: self._user_store.update_last_login(username)
            self.audit.add("LOGIN_SUCCESS", username=username, ip_address=ip_address,
                           details=f"Session created, role={user_info.get('role','user')}")
            return session
        self.audit.add("LOGIN_FAILURE", username=username or "unknown", ip_address=ip_address,
                       details=f"Invalid credentials for '{username}'")
        return None

    def register_user(self, username, password, invite_code, ip_address=""):
        if not self._user_store: return False, "Registration not available"
        if not self._code_store: return False, "Registration codes not configured"
        valid, err = self._code_store.validate_code(invite_code)
        if not valid:
            self.audit.add("LOGIN_FAILURE", username=username or "unknown", ip_address=ip_address,
                           details=f"Registration failed: {err}")
            return False, err
        u_err = _validate_username(username)
        if u_err: return False, u_err
        p_err = _validate_password_strength(password)
        if p_err: return False, p_err
        if self._user_store.get_user(username): return False, "Username already exists"
        role = "admin" if not self._user_store.has_admin() else "user"
        if self._user_store.add_user(username, password, role=role):
            self._code_store.consume_code(invite_code, username)
            self.audit.add("USER_REGISTER", username=username, ip_address=ip_address,
                           details=f"Registered with code, role={role}")
            self.audit.add("REGCODE_USED", username=username, ip_address=ip_address,
                           details=f"Code {invite_code[:12]}... used")
            return True, f"User '{username}' registered successfully"
        return False, "Failed to create user"

    def generate_registration_code(self, created_by, max_uses=1, expires_hours=None, note="", ip_address=""):
        if not self._code_store: return None, "Code store not configured"
        code = self._code_store.generate_code(created_by, max_uses, expires_hours, note)
        self.audit.add("REGCODE_GENERATED", username=created_by, ip_address=ip_address,
                       details=f"Code generated: {code[:12]}... max_uses={max_uses} expires={expires_hours}h note={note}")
        return code, None

    def list_registration_codes(self):
        if not self._code_store: return []
        return self._code_store.list_codes()

    def revoke_registration_code(self, code, revoked_by, ip_address=""):
        if not self._code_store: return False
        if self._code_store.revoke_code(code):
            self.audit.add("REGCODE_REVOKED", username=revoked_by, ip_address=ip_address,
                           details=f"Code {code[:12]}... revoked")
            return True
        return False

    def delete_registration_code(self, code, deleted_by, ip_address=""):
        if not self._code_store: return False
        if self._code_store.delete_code(code):
            self.audit.add("REGCODE_REVOKED", username=deleted_by, ip_address=ip_address,
                           details=f"Code {code[:12]}... deleted")
            return True
        return False

    def change_password(self, username, current_password, new_password, ip_address=""):
        p_err = _validate_password_strength(new_password)
        if p_err: return False, p_err
        if new_password == current_password: return False, "New password must differ from current"
        if self._user_store:
            if not self._user_store.verify_password(username, current_password):
                return False, "Current password is incorrect"
            if self._user_store.change_password(username, new_password):
                self.audit.add("PASSWORD_CHANGE", username=username, ip_address=ip_address, details="Password changed")
                return True, "Password changed successfully"
            return False, "User not found"
        else:
            if not _verify_password(current_password, self._default_salt, self._default_hash):
                return False, "Current password is incorrect"
            self._default_salt, self._default_hash = _hash_password(new_password)
            self.audit.add("PASSWORD_CHANGE", username=username, ip_address=ip_address, details="Password changed")
            return True, "Password changed successfully"

    def reset_password(self, username, new_password, reset_by, ip_address=""):
        if not self._user_store: return False, "Not available"
        p_err = _validate_password_strength(new_password)
        if p_err: return False, p_err
        if not self._user_store.get_user(username): return False, "User not found"
        if self._user_store.change_password(username, new_password):
            self.audit.add("PASSWORD_RESET", username=username, ip_address=ip_address,
                           details=f"Reset by admin '{reset_by}'")
            return True, f"Password reset for '{username}'"
        return False, "Failed"

    def get_user_info(self, username):
        if self._user_store:
            u = self._user_store.get_user(username)
            if u: return {"username": username, "role": u.get("role","user"),
                          "created_at": u.get("created_at",""), "last_login": u.get("last_login",""),
                          "is_active": u.get("is_active",True), "password_changed_at": u.get("password_changed_at","")}
        elif username == self._default_admin:
            return {"username": username, "role": "admin", "created_at": "", "last_login": "",
                    "is_active": True, "password_changed_at": ""}
        return None

    def list_users(self):
        if self._user_store: return self._user_store.list_users()
        return [{"username": self._default_admin, "role": "admin", "created_at": "", "is_active": True, "last_login": ""}]

    def validate_session(self, token):
        if not token: return None
        with self._lock:
            s = self._sessions.get(token)
            if not s: return None
            if time.time() > s["expires_at"]:
                del self._sessions[token]
                self.audit.add("SESSION_EXPIRED", username=s["username"], ip_address=s.get("ip_address",""),
                               details="Session expired")
                return None
            return s.copy()

    def destroy_session(self, token):
        with self._lock: s = self._sessions.pop(token, None)
        if s: self.audit.add("LOGOUT", username=s["username"], ip_address=s.get("ip_address",""), details="Logged out")

    def _cleanup_expired(self):
        now = time.time()
        for t in [t for t, s in self._sessions.items() if now > s["expires_at"]]:
            s = self._sessions.pop(t, None)
            if s: self.audit.add("SESSION_EXPIRED", username=s["username"], ip_address=s.get("ip_address",""), details="Expired cleanup")

    def get_active_sessions(self):
        with self._lock:
            self._cleanup_expired()
            return [s.copy() for s in self._sessions.values()]